name: provision-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    env:
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_SUBNET_CAE: ${{ vars.AZURE_SUBNET_CAE }}
      AZURE_SUBNET_PE: ${{ vars.AZURE_SUBNET_PE }}
      AZURE_CLOUD: ${{ vars.AZURE_CLOUD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use DotNet SDK 8.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.402

      - name: Install .Net Aspire workload
        run: dotnet workload install aspire

      - name: Install AZD
        uses: Azure/setup-azd@v1.0.0
        # with:
        #   version: "1.9.6"

      - name: Rewrite Azure Credentials to old format if necessary
        run: |
          echo "Original AZURE_CREDENTIALS:"
          echo "${AZURE_CREDENTIALS}" | jq '.'

          if ! echo "${AZURE_CREDENTIALS}" | jq -e 'has("clientSecret")' > /dev/null; then
            AZURE_CREDENTIALS_REWRITTEN=$(echo "${AZURE_CREDENTIALS}" | jq -c --arg subscriptionId "${AZURE_SUBSCRIPTION_ID}" '{ clientId: .appId, displayName: .displayName, clientSecret: .password, tenantId: .tenant, subscriptionId: $subscriptionId }')
          else
            AZURE_CREDENTIALS_REWRITTEN=$(echo "${AZURE_CREDENTIALS}" | jq -c --arg subscriptionId "${AZURE_SUBSCRIPTION_ID}" '. + {subscriptionId: $subscriptionId}')
          fi
          echo "AZURE_CREDENTIALS_REWRITTEN=${AZURE_CREDENTIALS_REWRITTEN}" >> $GITHUB_ENV
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete existing folders used for previous deployments
        run: |

      - name: Set up infra folder based on deployment model
        run: |
          set -e
          DEPLOYMENT_MODEL=${{ vars.DEPLOYMENT_MODEL }}

          # Delete existing infra folder
          rm -rf infra
          rm -rf .azure

          # Copy infra folder based on deployment model
          if [ "$DEPLOYMENT_MODEL" == "public" ]; then
            cp -r infra.public infra
          else
            cp -r infra.private infra
          fi
        env:
          DEPLOYMENT_MODEL: ${{ vars.DEPLOYMENT_MODEL }}

      - name: Set execute permission on .sh and .ps1 scripts in the ./deploy folder
        run: chmod ugo+x deploy/*.sh deploy/*.ps1

      - name: Activate azure-ci.yaml for CI/CD deployment
        run: |
          rm -f azure.yaml
          cp azure-ci.yaml azure.yaml

      - name: Install text-based browsers for AZD authentication
        run: |
          sudo apt update -y
          sudo apt install lynx -y

      - name: Login with Azure CLI (Client Credentials)
        uses: Azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS_REWRITTEN }}
          environment: ${{ vars.AZURE_CLOUD }}

      - name: Log in with Azure Developer CLI (Client Credentials)
        if: ${{ env.AZURE_CREDENTIALS != '' }}
        run: |
          info=$(echo "${AZURE_CREDENTIALS}" | jq -r '.')
          client_id=$(echo "${info}" | jq -r '.appId // .clientId')
          client_secret=$(echo "${info}" | jq -r '.password // .clientSecret')
          tenant_id=$(echo "${info}" | jq -r '.tenant // .tenantId')

          # Set cloud.name to contents of AZURE_CLOUD
          # Display the current cloud name
          azd config set cloud.name ${AZURE_CLOUD}
          echo "Current AZD cloud name: $(az cloud show --query name -o tsv)"

          azd auth login \
            --client-id "${client_id}" \
            --client-secret "${client_secret}" \
            --tenant-id "${tenant_id}"
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          AZURE_CLOUD: ${{ vars.AZURE_CLOUD }}

      - name: Update Bicep file for workload profile type
        run: |
          WORKLOAD_TYPE="${{ env.AZURE_CAE_WORKLOAD_TYPE }}"

          # If the workload type is not set or empty, default to 'D4'
          if [ -z "$WORKLOAD_TYPE" ]; then
            WORKLOAD_TYPE="D4"
          fi

          # Replace the workload profile type in the Bicep file
          sed -i "s/param workloadProfileType string = 'D4'/param workloadProfileType string = '$WORKLOAD_TYPE'/" infra/resources.bicep

          echo "Updated resources.bicep with workload profile type: $WORKLOAD_TYPE"
          echo "DEBUG : Updated resources.bicep file:"
          cat infra/resources.bicep

        env:
          AZURE_CAE_WORKLOAD_TYPE: ${{ vars.AZURE_CAE_WORKLOAD_TYPE }}

      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}
          AZURE_CAE_WORKLOAD_TYPE: ${{ vars.AZURE_CAE_WORKLOAD_TYPE }}

      - name: Create appsettings.Production.json file
        run: |
          # Copy appsettings.json to appsettings.Production.json (in the Microsoft.Greenlight.AppHost directory)
          cp Microsoft.Greenlight.AppHost/appsettings.json Microsoft.Greenlight.AppHost/appsettings.Production.json

          # Ensure ConnectionStrings and ServiceConfiguration.AzureMaps objects exist and add respective fields
          jq --arg openai_planner "${openai_planner}" --arg azure_maps_key "${ServiceConfiguration__AzureMaps__Key}" '
            .ConnectionStrings = (.ConnectionStrings // {}) |
            .ConnectionStrings["openai-planner"] = $openai_planner |
            .ServiceConfiguration.AzureMaps = (.ServiceConfiguration.AzureMaps // {}) |
            .ServiceConfiguration.AzureMaps.Key = $azure_maps_key' \
            Microsoft.Greenlight.AppHost/appsettings.Production.json > Microsoft.Greenlight.AppHost/appsettings.Production.json.tmp

          # Move the temporary file to the final appsettings.Production.json
          mv Microsoft.Greenlight.AppHost/appsettings.Production.json.tmp Microsoft.Greenlight.AppHost/appsettings.Production.json

          # Display the full appsettings.Production.json file
          echo "*****************************************************************************************"
          cat Microsoft.Greenlight.AppHost/appsettings.Production.json
          echo "*****************************************************************************************"
        env:
          openai_planner: ${{ secrets.PVICO_OPENAI_CONNECTIONSTRING }}
          ServiceConfiguration__AzureMaps__Key: ${{ secrets.PVICO_AZUREMAPS_KEY }}

      - name: Add AzureAd configuration to appsettings.Production.json
        run: |
          # Check if the secret exists and is not empty
          if [ -z "${PVICO_ENTRA_CREDENTIALS}" ]; then
            echo "PVICO_ENTRA_CREDENTIALS is not set or is empty. Skipping AzureAd configuration."
            exit 0
          fi

          # Load the existing appsettings.Production.json into a variable
          appsettings=$(cat Microsoft.Greenlight.AppHost/appsettings.Production.json)

          # Load the AzureAd configuration from the secret
          azureAdConfig=$(echo "${PVICO_ENTRA_CREDENTIALS}")

          # Merge the AzureAd configuration into the appsettings under the "AzureAd" key
          merged=$(echo "${appsettings}" | jq --argjson azureAdConfig "${azureAdConfig}" '. + {AzureAd: $azureAdConfig}')

          # Write the merged configuration back to the appsettings.Production.json file
          echo "${merged}" > Microsoft.Greenlight.AppHost/appsettings.Production.json

          # Display the full appsettings.Production.json file
          echo "*****************************************************************************************"
          cat Microsoft.Greenlight.AppHost/appsettings.Production.json
          echo "*****************************************************************************************"
        env:
          PVICO_ENTRA_CREDENTIALS: ${{ secrets.PVICO_ENTRA_CREDENTIALS }}

      - name: Retrieve Managed Identity Client ID
        id: get_mi_client_id
        run: |
          RG_NAME="rg-${{ env.AZURE_ENV_NAME }}"
          # Get managed identity details
          MI_CLIENT_ID=$(az identity list -g "$RG_NAME" --query "[?starts_with(name, 'mi-')].clientId" -o tsv)

          # Fail if no managed identity is found
          if [ -z "$MI_CLIENT_ID" ]; then
            echo "Managed Identity not found in the resource group $RG_NAME."
            exit 1
          fi

          echo "MI_CLIENT_ID=$MI_CLIENT_ID" >> $GITHUB_ENV

      - name: Retrieve SQL Database Name from appsettings.Production.json
        id: get_db_name
        run: |
          # Extract SQL Database Name from appsettings.Production.json
          DB_NAME=$(jq -r '.ServiceConfiguration.SQL.DatabaseName' Microsoft.Greenlight.AppHost/appsettings.Production.json)

          # Fail if database name is not found
          if [ -z "$DB_NAME" ]; then
            echo "Database name not found in appsettings.Production.json."
            exit 1
          fi

          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV

      - name: Construct Connection String
        id: create_conn_string
        run: |
          # Get the SQL Server name (assuming it's the only SQL server in the resource group)
          RG_NAME="rg-${{ env.AZURE_ENV_NAME }}"
          SQL_SERVER_NAME=$(az sql server list -g "$RG_NAME" --query "[0].fullyQualifiedDomainName" -o tsv)

          # Check if SQL Server name is retrieved
          if [ -z "$SQL_SERVER_NAME" ]; then
            echo "SQL Server not found in the resource group $RG_NAME."
            exit 1
          fi

          # Construct the connection string
          CONNECTION_STRING="Server=tcp:$SQL_SERVER_NAME,1433;Database=$DB_NAME;Authentication=Active Directory Managed Identity;User Id=${{ env.MI_CLIENT_ID }};"
          echo "CONNECTION_STRING=$CONNECTION_STRING" >> $GITHUB_ENV

      - name: Run EF Core Migrations
        run: dotnet ef database update --project Microsoft.Greenlight.Shared --connection "$CONNECTION_STRING"
        env:
          CONNECTION_STRING: ${{ env.CONNECTION_STRING }}

      - name: Deploy Application
        run: azd deploy --no-prompt
        env:
          AZURE_RESOURCE_GROUP: rg-${{ env.AZURE_ENV_NAME }}
          AZURE_CAE_WORKLOAD_TYPE: ${{ vars.AZURE_CAE_WORKLOAD_TYPE }}
          PVICO_OPENAI_CONNECTIONSTRING: ${{ secrets.PVICO_OPENAI_CONNECTIONSTRING }}
          PVICO_OPENAI_RESOURCEGROUP: ${{ vars.PVICO_OPENAI_RESOURCEGROUP }}
