name: v2-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    env:
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_SUBNET_CAE: ${{ vars.AZURE_SUBNET_CAE }}
      AZURE_SUBNET_PE: ${{ vars.AZURE_SUBNET_PE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use DotNet SDK 8.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Install .Net Aspire workload
        run: dotnet workload install aspire

      - name: Delete existing folders used for previous deploymens
        run: |
          rm -rf infra
          rm -rf .azure

      - name: Set up infra folder based on deployment model
        run: |
          DEPLOYMENT_MODEL=${{ env.DEPLOYMENT_MODEL }}
          if [ "$DEPLOYMENT_MODEL" == "public" ]; then
            cp -r infra.public infra
          else
            cp -r infra.private infra
          fi
        env:
          DEPLOYMENT_MODEL: ${{ vars.DEPLOYMENT_MODEL }}
      - name: Set execute permission on .sh and .ps1 scripts in the ./deploy folder
        run: chmod ugo+x deploy/*.sh deploy/*.ps1

      - name: Activate azure-ci.yaml for CI/CD deployment
        run: |
          rm -f azure.yaml
          cp azure-ci.yaml azure.yaml

      - name: Install AZD
        uses: Azure/setup-azd@v1.0.0

      - name: Install text-based browsers for AZD authentication
        run: |
          sudo apt update -y
          sudo apt install lynx links2 elinks w3m -y

      - name: Login with Azure CLI (Client Credentials)
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in with Azure Developer CLI (Client Credentials)
        if: ${{ env.AZURE_CREDENTIALS != '' }}
        run: |
          info=$(echo "${AZURE_CREDENTIALS}" | jq -r '.')
          client_id=$(echo "${info}" | jq -r '.appId // .clientId')
          client_secret=$(echo "${info}" | jq -r '.password // .clientSecret')
          tenant_id=$(echo "${info}" | jq -r '.tenant // .tenantId')

          azd auth login \
            --client-id "${client_id}" \
            --client-secret "${client_secret}" \
            --tenant-id "${tenant_id}"
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}

      - name: Deploy Application
        run: azd deploy --no-prompt
        env:
          AZURE_RESOURCE_GROUP: rg-${{ env.AZURE_ENV_NAME }}
